/**
 * SHAYONA ENTERPRISES - ARCHITECTURAL PRODUCT CATALOGUE DATA
 * Digital Interior Material Showroom Dataset
 */

const categoriesData = [
  {
    id: "wall-panels",
    hash: "wall-panels",
    number: "01",
    name: "Wall Panels",
    tagline: "Architectural Surface Statements & Acoustic Relief",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/wall-panels.webp",
    description: "Explore decorative, textured and architectural wall surface solutions designed to add depth, character, acoustic warmth and spatial elegance to contemporary residential and commercial interiors.",
    productCountText: "16+ PRODUCTS AVAILABLE",
    subcategories: [
      "Decorative Wall Panels",
      "PVC Wall Panels",
      "WPC Wall Panels",
      "Fluted Wall Panels",
      "Charcoal Wall Panels",
      "Louvers Panels",
      "3D Wall Panels",
      "Stone Wall Panels",
      "PU Stone Panels",
      "Ceiling Panels",
      "Soffit Panels"
    ],
    products: [
      {
        id: "wp-01",
        name: "Decorative Wall Panel",
        category: "Wall Panels",
        subcategory: "Decorative Wall Panels",
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
        specs: "High-density embossed architectural wall panel with anti-scratch coating and moisture resistance.",
        material: "High-Density Engineered Composite",
        finish: "Natural Matte Texture",
        dimensions: "2440mm x 610mm x 12mm",
        applications: "Living Room Feature Walls, Master Bed Backdrops, Executive Cabins"
      },
      {
        id: "wp-02",
        name: "Decorative PVC Wall Panel",
        category: "Wall Panels",
        subcategory: "PVC Wall Panels",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
        specs: "100% waterproof virgin PVC panel with thermal insulation and termite-proof formulation.",
        material: "Virgin Polymer Composite",
        finish: "Satin Woodgrain Texture",
        dimensions: "2900mm x 300mm x 9mm",
        applications: "Moisture-Prone Walls, Kitchen Corridors, Modern Bathrooms"
      },
      {
        id: "wp-03",
        name: "Glossy Wooden Wall Panel",
        category: "Wall Panels",
        subcategory: "Decorative Wall Panels",
        image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
        specs: "High-gloss UV lacquered wood veneer effect panel offering brilliant depth and reflective luxury.",
        material: "Lacquered HDHMR Substrate",
        finish: "High Gloss Mirror UV Coat",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "Luxury Entrance Foyers, Dining Feature Walls, Penthouse Suites"
      },
      {
        id: "wp-04",
        name: "Decorative Metal Wall Panel",
        category: "Wall Panels",
        subcategory: "Decorative Wall Panels",
        image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        specs: "Brushed champagne gold and titanium finished architectural metal accent cladding.",
        material: "Anodized Aluminum / SS304 Inlay",
        finish: "Brushed Champagne Gold PVD",
        dimensions: "2440mm x 600mm x 10mm",
        applications: "Hotel Lobbies, High-End Reception Backdrops, Luxury Lounges"
      },
      {
        id: "wp-05",
        name: "Designer Louver Wall Panel",
        category: "Wall Panels",
        subcategory: "Louvers Panels",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        specs: "Calibrated interlocking louver profile creating rhythmic linear shadow gaps and acoustic dispersion.",
        material: "High Impact Polystyrene (HIPS)",
        finish: "Smoked American Walnut",
        dimensions: "2900mm x 160mm x 24mm",
        applications: "Living Areas, Home Theaters, Executive Office Feature Walls"
      },
      {
        id: "wp-06",
        name: "PVC Decorative Wall Panels",
        category: "Wall Panels",
        subcategory: "PVC Wall Panels",
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
        specs: "Lightweight, easy tongue-and-groove installation panels with UV-protected marble patterns.",
        material: "Extruded Rigid PVC",
        finish: "Calacatta Gold Polished Marble Look",
        dimensions: "2800mm x 400mm x 8mm",
        applications: "Corridors, Vanity Walls, Commercial Partitions"
      },
      {
        id: "wp-07",
        name: "PVC Fluted Wall Panel",
        category: "Wall Panels",
        subcategory: "Fluted Wall Panels",
        image: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=800&q=80",
        specs: "Precision fluted vertical wave pattern engineered for modern organic interior textures.",
        material: "Co-Extruded Rigid Polymer",
        finish: "Matte Sandstone & Warm Oak",
        dimensions: "2900mm x 120mm x 18mm",
        applications: "Curved Pillar Wraps, TV Unit Consoles, Accent Niches"
      },
      {
        id: "wp-08",
        name: "PVC False Ceiling Panel",
        category: "Wall Panels",
        subcategory: "Ceiling Panels",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
        specs: "Hollow-chamber lightweight ceiling panel offering acoustic dampening and integrated LED channels.",
        material: "Flame Retardant PVC",
        finish: "Architectural Off-White Matte",
        dimensions: "3000mm x 250mm x 7mm",
        applications: "False Ceilings, Balcony Overhangs, Modern Showrooms"
      },
      {
        id: "wp-09",
        name: "WPC Wall Panel",
        category: "Wall Panels",
        subcategory: "WPC Wall Panels",
        image: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=800&q=80",
        specs: "Heavy-duty Wood Polymer Composite with authentic natural wood grain and zero maintenance.",
        material: "Wood-Plastic Composite (70% Timber / 30% Polymer)",
        finish: "Weathered Teak Grain",
        dimensions: "2900mm x 200mm x 20mm",
        applications: "Interior Cladding, Semi-Outdoor Courtyards, Staircase Walls"
      },
      {
        id: "wp-10",
        name: "Fluted Wall Panel",
        category: "Wall Panels",
        subcategory: "Fluted Wall Panels",
        image: "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=800&q=80",
        specs: "Classic scalloped vertical fluting with seamless invisible interlocking tongue-and-groove joints.",
        material: "Architectural HD Polymer",
        finish: "Brushed Ash & Warm Charcoal",
        dimensions: "2900mm x 150mm x 15mm",
        applications: "Bed Headboards, Partition Panels, Dining Accents"
      },
      {
        id: "wp-11",
        name: "Louvers Charcoal Panel",
        category: "Wall Panels",
        subcategory: "Charcoal Wall Panels",
        image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=800&q=80",
        specs: "Infused activated charcoal panel with anti-bacterial qualities and deep matte charcoal finish.",
        material: "Charcoal Micro-Fiber Core",
        finish: "Anthracite Deep Matte Louver",
        dimensions: "2440mm x 120mm x 12mm",
        applications: "Lounge Bars, Modern Master Suites, Home Theaters"
      },
      {
        id: "wp-12",
        name: "Charcoal Wall Panels",
        category: "Wall Panels",
        subcategory: "Charcoal Wall Panels",
        image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80",
        specs: "Rich monolithic charcoal surface panels engineered for seamless architectural continuity.",
        material: "Charcoal Matrix Composite",
        finish: "Fine Velvet Textured Charcoal",
        dimensions: "2440mm x 1220mm x 8mm",
        applications: "Gallery Spaces, Minimalist Studios, Boutique Showrooms"
      },
      {
        id: "wp-13",
        name: "Charcoal Louver Panel",
        category: "Wall Panels",
        subcategory: "Louvers Panels",
        image: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?auto=format&fit=crop&w=800&q=80",
        specs: "Architectural dark louver panel with subtle bronze and metallic edge highlights.",
        material: "Dense Charcoal Polymer",
        finish: "Ebony Matte with Bronze Inlay Edge",
        dimensions: "2900mm x 155mm x 18mm",
        applications: "TV Units, Living Room Accent Walls, Hotel Suites"
      },
      {
        id: "wp-14",
        name: "Decorative Stone Sheets",
        category: "Wall Panels",
        subcategory: "Stone Wall Panels",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Flexible natural slate and quartzite stone veneer sheet with genuine mineral texture.",
        material: "100% Real Split Stone on Fiberglass Backing",
        finish: "Natural Slate Rough Split Texture",
        dimensions: "2440mm x 1220mm x 2.5mm",
        applications: "Feature Fireplaces, Curved Stone Walls, Column Encasements"
      },
      {
        id: "wp-15",
        name: "PU Stone Panel",
        category: "Wall Panels",
        subcategory: "PU Stone Panels",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
        specs: "High-density polyurethane faux stone replica with hyper-realistic 3D geological relief.",
        material: "Molded High-Density Polyurethane (PU)",
        finish: "Rough Cut Limestone / Travertine Relief",
        dimensions: "1200mm x 600mm x 35mm",
        applications: "Landscape Courtyards, Rustic Interior Accents, Villa Lobbies"
      },
      {
        id: "wp-16",
        name: "PVC Soffit Ceiling Panel",
        category: "Wall Panels",
        subcategory: "Soffit Panels",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        specs: "Perforated/solid soffit panels engineered for exterior overhangs and interior high-humidity areas.",
        material: "UV-Stabilized Cellular PVC",
        finish: "Golden Oak & Arctic White",
        dimensions: "3000mm x 300mm x 10mm",
        applications: "Porch Ceilings, Balconies, Bathroom Suspended Ceilings"
      }
    ]
  },
  {
    id: "doors",
    hash: "doors",
    number: "02",
    name: "Doors",
    tagline: "Architectural Entrances & Handcrafted Passage Joinery",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/doors.webp",
    description: "Discover bespoke entrance statements, laminated flush doors, solid hardwoods, and specialized acoustic doors precision-engineered with structural timber cores and luxury finishes.",
    productCountText: "19+ PRODUCTS AVAILABLE",
    subcategories: [
      "Flush Doors",
      "Wooden Doors",
      "PVC Doors",
      "WPC Doors",
      "Designer Doors",
      "Bathroom Doors",
      "Mesh Doors"
    ],
    products: [
      {
        id: "dr-01",
        name: "Wooden Flush Door",
        category: "Doors",
        subcategory: "Flush Doors",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Kiln-seasoned hardwood core with BWP grade bonding and calibrated flat surface.",
        material: "Hardwood Pine Core with Gurjan Crossbands",
        finish: "Ready for Polish / Paint / Laminate",
        dimensions: "2100mm x 900mm x 32mm / 38mm",
        applications: "Bedrooms, Main Entrances, Internal Partitions"
      },
      {
        id: "dr-02",
        name: "Laminated Flush Door",
        category: "Doors",
        subcategory: "Flush Doors",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "Factory pre-laminated flush door with seamless edge-banding and scratch-proof surface.",
        material: "BWP Flush Door Core + 1mm High-Pressure Laminate",
        finish: "Dual Tone Suede Walnut & Ash",
        dimensions: "2100mm x 900mm x 35mm",
        applications: "Apartment Entrances, Office Cabins, Hotel Guest Rooms"
      },
      {
        id: "dr-03",
        name: "Pine Wood Flush Door",
        category: "Doors",
        subcategory: "Wooden Doors",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "Solid New Zealand pine wood stiles and rails with anti-warp structural calibration.",
        material: "100% Seasoned Pinewood",
        finish: "Natural Honey Pine Polyurethane Coating",
        dimensions: "2100mm x 850mm x 35mm",
        applications: "Living Spaces, Villa Internal Doors, Study Rooms"
      },
      {
        id: "dr-04",
        name: "Sagwan Wooden Door",
        category: "Doors",
        subcategory: "Wooden Doors",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Heirloom grade pure CP Teak (Sagwan) wood with handcrafted relief panels.",
        material: "Authentic Central Province Teakwood",
        finish: "Hand-Rubbed Linseed Oil & Italian PU Gloss",
        dimensions: "2100mm x 1000mm x 45mm",
        applications: "Grand Residence Main Gateways, Temple Doors"
      },
      {
        id: "dr-05",
        name: "Solid Wood Panel Door",
        category: "Doors",
        subcategory: "Wooden Doors",
        image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80",
        specs: "Traditional 6-panel solid wood construction with mortise and tenon joint integrity.",
        material: "Seasoned Red Meranti / Oak",
        finish: "Dark Antique Walnut Stain",
        dimensions: "2100mm x 900mm x 40mm",
        applications: "Classic Architectural Villas, Colonial Interiors"
      },
      {
        id: "dr-06",
        name: "Wooden Laminated Door",
        category: "Doors",
        subcategory: "Designer Doors",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "CNC grooved wooden patterns overlaid with thermal-pressed textured wood foil.",
        material: "Engineered Hardwood with CNC Groove",
        finish: "Smoked Oak Woodgrain Texture",
        dimensions: "2100mm x 900mm x 35mm",
        applications: "Contemporary Bedrooms, Suite Entrances"
      },
      {
        id: "dr-07",
        name: "Designer Laminate Flush Door",
        category: "Doors",
        subcategory: "Designer Doors",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "Geometric brass metal strip inlays integrated into luxury dark wood laminate.",
        material: "BWP Marine Core + Brass Inlays",
        finish: "Matte Charcoal & Champagne Gold PVD Trim",
        dimensions: "2200mm x 950mm x 38mm",
        applications: "Luxury Apartment Main Entrances"
      },
      {
        id: "dr-08",
        name: "Decorative Designer Door",
        category: "Doors",
        subcategory: "Designer Doors",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Multi-tiered 3D sculptural door with textured relief art and integrated mortise lock housing.",
        material: "HDHMR & Polyurethane Sculpting",
        finish: "Metallic Bronze / Textured Patina",
        dimensions: "2400mm x 1050mm x 45mm",
        applications: "Bespoke Residence Entrance Statement"
      },
      {
        id: "dr-09",
        name: "HDHMR Designer Door",
        category: "Doors",
        subcategory: "Designer Doors",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "High Density High Moisture Resistance board door with sharp CNC precision carvings.",
        material: "Action TESA / Greenply HDHMR Board",
        finish: "Italian PU Paint Matte White / Grey",
        dimensions: "2100mm x 900mm x 35mm",
        applications: "Modern Penthouse Interiors, Clean Minimalist Spaces"
      },
      {
        id: "dr-10",
        name: "HDHMR Carving Door",
        category: "Doors",
        subcategory: "Designer Doors",
        image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80",
        specs: "Deep 3D CNC bas-relief carving depicting traditional or contemporary geometric artwork.",
        material: "Heavy Density HDHMR Substrate",
        finish: "Multi-layered Deco PU Finish",
        dimensions: "2100mm x 900mm x 38mm",
        applications: "Puja Room Entrances, Feature Gateway Doors"
      },
      {
        id: "dr-11",
        name: "PVC Bathroom Door",
        category: "Doors",
        subcategory: "Bathroom Doors",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "100% moisture and steam proof hollow-grid PVC construction with reinforced lock block.",
        material: "Extruded Rigid PVC",
        finish: "Frosted Glass & Wood Print",
        dimensions: "2000mm x 750mm x 30mm",
        applications: "Bathrooms, Restrooms, Wet Utilities"
      },
      {
        id: "dr-12",
        name: "Wooden Texture PVC Door",
        category: "Doors",
        subcategory: "PVC Doors",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Realistic warm woodgrain film bonded over heavy-gauge PVC structure.",
        material: "Thermal-Formed Heavy PVC",
        finish: "Teak & Rosewood Grain Emboss",
        dimensions: "2050mm x 800mm x 30mm",
        applications: "Utility Balcony Doors, Powder Rooms"
      },
      {
        id: "dr-13",
        name: "Decorative PVC Door",
        category: "Doors",
        subcategory: "PVC Doors",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "Designer printed and embossed panel door for cost-effective moisture resistance.",
        material: "UV Coated PVC Membrane",
        finish: "Gloss Floral / Geometric Motif",
        dimensions: "2000mm x 750mm x 28mm",
        applications: "Residential Bathrooms, Staff Quarters"
      },
      {
        id: "dr-14",
        name: "WPC Bathroom Door",
        category: "Doors",
        subcategory: "WPC Doors",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "Solid Wood Polymer Composite door with 100% termite proof and 0% water absorption rating.",
        material: "Solid Die-Cast WPC Board",
        finish: "CNC Grooved PU Lacquer",
        dimensions: "2100mm x 750mm x 30mm",
        applications: "Master Bathrooms, Wet Spas, Terrace Access"
      },
      {
        id: "dr-15",
        name: "Fiber Bathroom Door",
        category: "Doors",
        subcategory: "Bathroom Doors",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
        specs: "Glass Reinforced Polymer (FRP) molded door with extreme chemical and moisture durability.",
        material: "Heavy-Gauge FRP (Fiber Reinforced Plastic)",
        finish: "Cast White Woodgrain Texture",
        dimensions: "2000mm x 750mm x 32mm",
        applications: "Commercial Restrooms, Industrial Bathrooms"
      },
      {
        id: "dr-16",
        name: "Mesh Door",
        category: "Doors",
        subcategory: "Mesh Doors",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Hardwood frame door fitted with high-tensile SS304 anti-rust wire mesh for ventilation.",
        material: "Teakwood Frame + SS304 Black Wire Mesh",
        finish: "Natural Teak Oil Finish",
        dimensions: "2100mm x 900mm x 32mm",
        applications: "Main Entrance Outer Security Gate, Balconies"
      },
      {
        id: "dr-17",
        name: "Mosquito Net Door",
        category: "Doors",
        subcategory: "Mesh Doors",
        image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80",
        specs: "Pleated or magnetic fly screen mesh door built into architectural aluminum frames.",
        material: "Extruded Architectural Aluminum + Fiberglass Mesh",
        finish: "Powder Coated Charcoal Bronze",
        dimensions: "Custom Architectural Sizes",
        applications: "French Doors, Sliding Balcony Openings"
      },
      {
        id: "dr-18",
        name: "Readymade Mesh Door",
        category: "Doors",
        subcategory: "Mesh Doors",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Factory pre-hung wire mesh door ready for rapid installation with pre-fitted hardware.",
        material: "Calibrated Timber & Stainless Mesh",
        finish: "Walnut Stain & Matte Black Hardware",
        dimensions: "2100mm x 850mm x 30mm",
        applications: "Kitchen Verandahs, Rear Garden Access"
      },
      {
        id: "dr-19",
        name: "Teak Wood Door",
        category: "Doors",
        subcategory: "Wooden Doors",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Solid Burma Teak with rich golden-brown grain, natural oily resistance, and brass joinery.",
        material: "100% Seasoned Burma Teak",
        finish: "Hand-Polished Satin Wax / Polyurethane",
        dimensions: "2400mm x 1100mm x 50mm",
        applications: "Ultra-Luxury Villas, Private Estate Portals"
      }
    ]
  },
  {
    id: "laminates",
    hash: "laminates",
    number: "03",
    name: "Laminates",
    tagline: "High-Pressure Tactile Surfaces & Decorative Highlighters",
    image: "https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/laminates.webp",
    description: "Discover curated high-pressure decorative laminates, anti-fingerprint silks, tactile woodgrains, stone textures, and door skin finishes engineered for superior scratch and stain resistance.",
    productCountText: "13+ PRODUCTS AVAILABLE",
    subcategories: [
      "Decorative Laminates",
      "Wooden Laminates",
      "Premium Laminates",
      "Door Laminates",
      "Printed Laminates",
      "Mica & Sunmica"
    ],
    products: [
      {
        id: "lm-01",
        name: "Waterproof Laminate Sheet",
        category: "Laminates",
        subcategory: "Decorative Laminates",
        image: "https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=800&q=80",
        specs: "100% phenolic resin core high-pressure laminate with zero water swell and microbial barrier.",
        material: "Kraft Paper + Phenolic Resin (1.0mm)",
        finish: "Micro-Texture Satin Matte",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Kitchen Cabinets, Vanity Counters, Lab Worktops"
      },
      {
        id: "lm-02",
        name: "Wardrobe Laminate Sheet",
        category: "Laminates",
        subcategory: "Decorative Laminates",
        image: "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=800&q=80",
        specs: "Subtle textured fabric and leather effect laminate for luxurious internal wardrobe carcasses.",
        material: "Decorative Paper with Melamine Overlay",
        finish: "Linen & Leather Tactile Emboss",
        dimensions: "2440mm x 1220mm x 0.8mm",
        applications: "Walk-in Closets, Chest of Drawers, Bed Storage"
      },
      {
        id: "lm-03",
        name: "Rustic Laminate",
        category: "Laminates",
        subcategory: "Wooden Laminates",
        image: "https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=800&q=80",
        specs: "Deep synchronous register wood grain that perfectly follows the visual sawmill knots.",
        material: "Synchronized High-Pressure Laminate",
        finish: "Rough Sawn Smoked Oak",
        dimensions: "2440mm x 1220mm x 1.25mm",
        applications: "Dining Tables, Living Consoles, Study Desks"
      },
      {
        id: "lm-04",
        name: "Velvet Laminate",
        category: "Laminates",
        subcategory: "Premium Laminates",
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
        specs: "Ultra-matte anti-fingerprint thermal healing surface with velvety soft-touch feel.",
        material: "Electron-Beam Cured Surface Layer",
        finish: "Zero Reflection Super Matte",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Contemporary Modular Kitchens, High-End Workstations"
      },
      {
        id: "lm-05",
        name: "Decorative Laminate Sheet",
        category: "Laminates",
        subcategory: "Decorative Laminates",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
        specs: "Bold geometric and stone patterns calibrated for accent furniture and wall paneling.",
        material: "High Pressure Melamine Laminate",
        finish: "Terrazzo & Concrete Polish",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Feature Cabinets, Coffee Tables, Wall Cladding"
      },
      {
        id: "lm-06",
        name: "Wood Laminate Sheet",
        category: "Laminates",
        subcategory: "Wooden Laminates",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Natural American Walnut grain reproduction with warm golden undertones.",
        material: "Thermoset Phenolic Substrate",
        finish: "Crown Cut Natural Walnut",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Living Room Millwork, TV Backdrops, Sideboards"
      },
      {
        id: "lm-07",
        name: "Wooden Laminate Sheet",
        category: "Laminates",
        subcategory: "Wooden Laminates",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "Scandinavian Light Ash and Bleached Oak surface for luminous, airy minimalist interiors.",
        material: "High Grade Melamine Resin Sheet",
        finish: "Fine Pore Scandinavian Ash",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Modern Apartments, Children Rooms, Cafe Tables"
      },
      {
        id: "lm-08",
        name: "Sunmica Laminate",
        category: "Laminates",
        subcategory: "Mica & Sunmica",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "Trusted standard decorative mica sheet offering extreme scratch and boiling water resistance.",
        material: "Standard Kraft & Decorative Layers",
        finish: "Suede & Gloss Multi-Finish",
        dimensions: "2440mm x 1220mm x 0.8mm - 1.0mm",
        applications: "Everyday Commercial & Residential Joinery"
      },
      {
        id: "lm-09",
        name: "Cane Laminate",
        category: "Laminates",
        subcategory: "Premium Laminates",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
        specs: "Embossed woven rattan cane texture providing bohemian and Japandi warmth without organic wear.",
        material: "3D Textured High-Pressure Polymer",
        finish: "Woven Natural Cane Emboss",
        dimensions: "2440mm x 1220mm x 1.2mm",
        applications: "Wardrobe Shutters, Sideboard Doors, Shoe Consoles"
      },
      {
        id: "lm-10",
        name: "Premium Silk Laminate",
        category: "Laminates",
        subcategory: "Premium Laminates",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Subtle satin sheen that diffuses ambient room lighting with champagne and ivory tones.",
        material: "Optical Grade Satin Resin",
        finish: "Pure Silk Touch",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Luxury Kitchen Overhead Cabinets, Master Dressers"
      },
      {
        id: "lm-11",
        name: "Designer Laminate Sheet",
        category: "Laminates",
        subcategory: "Decorative Laminates",
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
        specs: "Metallic shimmer infused mica with brushed copper and oxidized metal accents.",
        material: "Metal Foil Infused HPL",
        finish: "Brushed Bronze Patina",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Bar Units, Reception Desks, Niche Accents"
      },
      {
        id: "lm-12",
        name: "Teak Wood Laminate",
        category: "Laminates",
        subcategory: "Wooden Laminates",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Authentic golden teakwood pattern with deep vertical striations and natural oil glow.",
        material: "Heavy-Gauge Kraft Phenolic",
        finish: "Quarter Sawn Teak Texture",
        dimensions: "2440mm x 1220mm x 1.0mm",
        applications: "Door Frames, Executive Millwork, Wall Paneling"
      },
      {
        id: "lm-13",
        name: "Door Skin Laminate",
        category: "Laminates",
        subcategory: "Door Laminates",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "Calibrated single-sheet door skin designed for seamless 7ft x 3ft and 8ft x 4ft door cladding.",
        material: "Pre-Cut Melamine Door Membrane",
        finish: "Contemporary Dual Tone Geometric Wood",
        dimensions: "2135mm x 915mm x 1.0mm",
        applications: "Flush Door Facing, Main Entry Doors"
      }
    ]
  },
  {
    id: "plywood-boards",
    hash: "plywood-boards",
    number: "04",
    name: "Plywood & Boards",
    tagline: "Structural Timber Cores & Calibrated Engineered Substrates",
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/plywood-boards.webp",
    description: "Certified BWP marine plywood, Gurjan cores, high-density HDHMR boards, moisture-resistant MDF, and cement fiber sheets engineered for zero-deflection architectural joinery.",
    productCountText: "15+ PRODUCTS AVAILABLE",
    subcategories: [
      "Commercial Plywood",
      "Marine Plywood",
      "MDF Boards",
      "HDHMR Boards",
      "Particle Boards",
      "Cement Boards"
    ],
    products: [
      {
        id: "pb-01",
        name: "PM Ply Plywood",
        category: "Plywood & Boards",
        subcategory: "Commercial Plywood",
        image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80",
        specs: "Calibrated commercial grade plywood with uniform thickness and high nail-holding capacity.",
        material: "Hardwood Timber with MR Grade Resin",
        finish: "Smooth Sanded Face Veneer",
        dimensions: "2440mm x 1220mm x (6mm/12mm/18mm)",
        applications: "Living Room Furniture, Dry Area Paneling, Office Desks"
      },
      {
        id: "pb-02",
        name: "CenturyPly",
        category: "Plywood & Boards",
        subcategory: "Marine Plywood",
        image: "https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=800&q=80",
        specs: "Industry-benchmark ViroKill technology with 100% borer and termite proof lifetime warranty.",
        material: "Selected Hardwood with BWP Phenolic Resin",
        finish: "Calibrated Double-Sided Sanded",
        dimensions: "2440mm x 1220mm x 19mm",
        applications: "Kitchen Under-Sink Cabinets, Luxury Wardrobes, Partitions"
      },
      {
        id: "pb-03",
        name: "BWR Commercial Plywood",
        category: "Plywood & Boards",
        subcategory: "Commercial Plywood",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Boiling Water Resistant resin bonded plywood suitable for high humidity Indian climates.",
        material: "Alternating Hardwood Veneers + Melamine Urea Formaldehyde",
        finish: "Fine Calibrated",
        dimensions: "2440mm x 1220mm x 12mm / 18mm",
        applications: "Modular Kitchen Carcasses, Washbasin Under-Counters"
      },
      {
        id: "pb-04",
        name: "BWP Grade Plywood",
        category: "Plywood & Boards",
        subcategory: "Marine Plywood",
        image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80",
        specs: "Boiling Waterproof 72-hour test certified marine timber engineered for permanent wet exposure.",
        material: "100% Phenol Formaldehyde Synthetic Resin",
        finish: "Gurjan Face Sanded",
        dimensions: "2440mm x 1220mm x 19mm",
        applications: "Bathroom Vanities, Kitchen Wet Zones, Outdoor Furniture"
      },
      {
        id: "pb-05",
        name: "Marine Plywood",
        category: "Plywood & Boards",
        subcategory: "Marine Plywood",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "IS:710 certified pure marine timber with unextended phenolic resin bonding.",
        material: "High Density Marine Hardwood",
        finish: "Zero-Core Gap Calibrated",
        dimensions: "2440mm x 1220mm x 16mm / 19mm",
        applications: "Luxury Wet Joinery, Yacht Interiors, Exterior Cladding Bases"
      },
      {
        id: "pb-06",
        name: "Gurjan Plywood",
        category: "Plywood & Boards",
        subcategory: "Marine Plywood",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "100% imported Gurjan wood core and face veneers offering supreme density and flexural strength.",
        material: "Pure Gurjan Hardwood (850 kg/m³)",
        finish: "Smooth Reddish-Brown Face",
        dimensions: "2440mm x 1220mm x 19mm",
        applications: "Heavy Duty Load Bearing Joinery, Architectural Beams"
      },
      {
        id: "pb-07",
        name: "Waterproof Plywood",
        category: "Plywood & Boards",
        subcategory: "Commercial Plywood",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
        specs: "Chemically vacuum pressure impregnated plywood resistant to dry rot and fungal decay.",
        material: "Treated Plantation Hardwood",
        finish: "Sanded Grade A/B",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "General Residential Millwork, Partition Frameworks"
      },
      {
        id: "pb-08",
        name: "Pine Wood Plywood",
        category: "Plywood & Boards",
        subcategory: "Commercial Plywood",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Lightweight, stable pinewood cross-laminated board with clean edges and easy machining.",
        material: "New Zealand Radiata Pine",
        finish: "Clear Blonde Sanded",
        dimensions: "2440mm x 1220mm x 12mm / 18mm",
        applications: "Exhibition Booths, Light Cabinetry, Wall Framing"
      },
      {
        id: "pb-09",
        name: "HDHMR Board",
        category: "Plywood & Boards",
        subcategory: "HDHMR Boards",
        image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
        specs: "High Density High Moisture Resistance green core board (850+ kg/m³) perfect for CNC routing.",
        material: "Eucalyptus Agro-Wood Fiber + Special Resin",
        finish: "Mirror Smooth Machine Sanded",
        dimensions: "2440mm x 1220mm x (12mm/16.75mm/18mm)",
        applications: "Modular Kitchen Shutters, CNC Jali Cutting, Wardrobe Doors"
      },
      {
        id: "pb-10",
        name: "MDF Board",
        category: "Plywood & Boards",
        subcategory: "MDF Boards",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        specs: "Uniform density Medium Density Fiberboard engineered for flawless paint and lacquer finishing.",
        material: "Refined Wood Fibers",
        finish: "Super Smooth Calibrated Surface",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "Mouldings, Speaker Enclosures, Painted Furniture"
      },
      {
        id: "pb-11",
        name: "Greenply MDF",
        category: "Plywood & Boards",
        subcategory: "MDF Boards",
        image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        specs: "Low formaldehyde emission E0/E1 grade MDF engineered for healthy indoor air quality.",
        material: "Hardwood Agro-Fibers",
        finish: "Dual-Sided Polished Sanded",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "Children Furniture, Hospital Interiors, Luxury Bedrooms"
      },
      {
        id: "pb-12",
        name: "Prelaminated MDF",
        category: "Plywood & Boards",
        subcategory: "MDF Boards",
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
        specs: "Factory hot-pressed melamine paper bonded to MDF substrate on both sides.",
        material: "MDF Core + Melamine Impregnated Paper",
        finish: "Bavarian Beech & Frosty White",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "Office Workstations, Bookshelves, Modular Racks"
      },
      {
        id: "pb-13",
        name: "Particle Board",
        category: "Plywood & Boards",
        subcategory: "Particle Boards",
        image: "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=800&q=80",
        specs: "Three-layer density particle board offering structural economy and uniform flatness.",
        material: "Wood Chips with Resin Binder",
        finish: "Sanded / Plain",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "Ready-to-Assemble Furniture, Modular Internal Partitions"
      },
      {
        id: "pb-14",
        name: "Cement Fiber Board",
        category: "Plywood & Boards",
        subcategory: "Cement Boards",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Autoclaved reinforced cement composite board offering Class 1 fire rating and termite immunity.",
        material: "Portland Cement + Cellulose Fibers",
        finish: "Matte Stone Grey",
        dimensions: "2440mm x 1220mm x 12mm",
        applications: "Drywall Partitions, Wet Tile Backer Board, Duct Enclosures"
      },
      {
        id: "pb-15",
        name: "Fiber Cement Sheet",
        category: "Plywood & Boards",
        subcategory: "Cement Boards",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
        specs: "Weather-resistant exterior cladding and false ceiling cement board with high acoustic rating.",
        material: "Non-Asbestos Fiber Reinforced Cement",
        finish: "Smooth / Woodgrain Textured",
        dimensions: "2440mm x 1220mm x 8mm",
        applications: "Exterior Eaves, Acoustical Ceiling Baffles, Facades"
      }
    ]
  },
  {
    id: "acrylic-sheets",
    hash: "acrylic-sheets",
    number: "05",
    name: "Acrylic & Decorative Sheets",
    tagline: "High-Gloss Mirror Lusters & Translucent Alabaster Surfaces",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/acrylic-sheets.webp",
    description: "Architectural 6H scratch-resistant acrylic sheets, backlit alabaster, fluted acrylics, charcoal highlighters, and ultra-gloss panels crafted for striking modern spatial highlights.",
    productCountText: "12+ PRODUCTS AVAILABLE",
    subcategories: [
      "Acrylic Sheets",
      "Decorative Acrylic",
      "Mirror Acrylic",
      "Charcoal Sheets",
      "Stone Veneer",
      "Alabaster Sheets"
    ],
    products: [
      {
        id: "ac-01",
        name: "Acrylic Plain Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Acrylic Sheets",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
        specs: "92% optical clarity virgin PMMA acrylic sheet with high UV and yellowing resistance.",
        material: "Virgin Cast Polymethyl Methacrylate",
        finish: "Crystal Clear Glass Luster",
        dimensions: "2440mm x 1220mm x (2mm/3mm/5mm)",
        applications: "Display Vitrines, Skylights, Protective Desk Glass Replacement"
      },
      {
        id: "ac-02",
        name: "Acrylic Mirror Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Mirror Acrylic",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Shatter-proof lightweight reflective mirror sheet in Silver, Gold, and Rose Gold shades.",
        material: "Vacuum Metallized Acrylic",
        finish: "Optical Mirror Reflection (Champagne Gold)",
        dimensions: "2440mm x 1220mm x 2mm / 3mm",
        applications: "Ceiling Mirror Panels, Gym Partitions, Wardrobe Inserts"
      },
      {
        id: "ac-03",
        name: "Marble Acrylic Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Decorative Acrylic",
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
        specs: "High-definition Italian marble veining embedded under 2mm scratch-proof acrylic coat.",
        material: "Cast Acrylic + Multi-Layer Mineral Print",
        finish: "Statuario Gold High Gloss Luster",
        dimensions: "2440mm x 1220mm x 2mm",
        applications: "Kitchen Dado Backsplashes, Vanity Backdrops, Lift Lobbies"
      },
      {
        id: "ac-04",
        name: "High Gloss Acrylic Panel",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Acrylic Sheets",
        image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
        specs: "6H pencil hardness scratch-resistant European acrylic laminated onto HDHMR board.",
        material: "1.5mm Acrylic + 18mm HDHMR Core",
        finish: "Piano Gloss Jet Black & Pure White",
        dimensions: "2440mm x 1220mm x 19.5mm",
        applications: "High-End Modular Kitchen Shutters, Bar Counters"
      },
      {
        id: "ac-05",
        name: "Fluted Glass Acrylic",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Decorative Acrylic",
        image: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=800&q=80",
        specs: "Molded reeded fluted acrylic surface providing graceful light diffusion and privacy.",
        material: "Linear Reeded Extruded Acrylic",
        finish: "Frosted / Clear Fluted Ribs",
        dimensions: "2440mm x 1220mm x 3mm / 4mm",
        applications: "Partition Screens, Cabinet Glazing, Backlit Bar Backdrops"
      },
      {
        id: "ac-06",
        name: "Designer Fluted Acrylic Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Decorative Acrylic",
        image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        specs: "Metallic tinted fluted acrylic with champagne, smoked grey, and amber luminous tones.",
        material: "Tinted Polymer with 3D Fluting",
        finish: "Smoked Bronze Fluted Satin",
        dimensions: "2440mm x 1220mm x 3mm",
        applications: "Boutique Display Windows, Wardrobe Inserts, Hotel Partitions"
      },
      {
        id: "ac-07",
        name: "Designer Charcoal Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Charcoal Sheets",
        image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=800&q=80",
        specs: "Embossed 3D geometric and botanical charcoal highlighter sheet with metallic foil highlights.",
        material: "Activated Charcoal Composite + Hot Foil",
        finish: "Matt Anthracite with Gold Vein",
        dimensions: "2440mm x 1220mm x 4mm",
        applications: "TV Console Highlighting, Bedroom Focal Walls"
      },
      {
        id: "ac-08",
        name: "Charcoal Highlighter Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Charcoal Sheets",
        image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80",
        specs: "Sculpted leather and mosaic relief sheet designed for dramatic vertical architectural bands.",
        material: "Flexible Charcoal Polymer",
        finish: "Deep Relief Textured Grey",
        dimensions: "2440mm x 600mm x 5mm",
        applications: "Pillar Cladding, Entrance Foyers, Dining Nooks"
      },
      {
        id: "ac-09",
        name: "Stone Veneer Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Stone Veneer",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Ultra-thin flexible split natural stone layer bonded to translucent or opaque polymer backing.",
        material: "Real Indian Quartzite & Slate",
        finish: "Natural Cleft Mineral Surface",
        dimensions: "2440mm x 1220mm x 2.0mm",
        applications: "Curved Reception Desks, Feature Columns, Light Boxes"
      },
      {
        id: "ac-10",
        name: "Backlight Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Alabaster Sheets",
        image: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?auto=format&fit=crop&w=800&q=80",
        specs: "Even-diffusion luminous acrylic panel designed for rear LED lighting without hot spots.",
        material: "Optically Diffusing Acrylic Compound",
        finish: "Milky Translucent Satin",
        dimensions: "2440mm x 1220mm x 4mm",
        applications: "Backlit Ceilings, Luminous Walls, Bar Fronts"
      },
      {
        id: "ac-11",
        name: "Onyx Alabaster Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Alabaster Sheets",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        specs: "Translucent synthetic onyx casting replicating deep honey and amber crystalline geological strata.",
        material: "Polyester Resin & Mineral Powder",
        finish: "Honey Onyx High Gloss Translucent",
        dimensions: "2440mm x 1220mm x 6mm / 8mm",
        applications: "Temple Backdrops, Backlit Reception Counters, Bar Podiums"
      },
      {
        id: "ac-12",
        name: "Light Passing Sheet",
        category: "Acrylic & Decorative Sheets",
        subcategory: "Alabaster Sheets",
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
        specs: "White alabaster sheet with delicate grey clouds engineered for ambient ethereal backlighting.",
        material: "Mineral-Infused Translucent Composite",
        finish: "Calacatta Alabaster Soft Satin",
        dimensions: "2440mm x 1220mm x 6mm",
        applications: "Backlit Headboards, Luxury Spa Partitions, False Ceilings"
      }
    ]
  },
  {
    id: "mouldings-profiles",
    hash: "mouldings-profiles",
    number: "06",
    name: "Mouldings & Profiles",
    tagline: "Architectural Cornices, Wainscoting & Metallic Accent Trims",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/mouldings-profiles.webp",
    description: "Classic European wall mouldings, French wainscoting frames, HDHMR profiles, and stainless steel PVD gold T/U/L trims crafted to give walls refined architectural proportion.",
    productCountText: "7+ PRODUCTS AVAILABLE",
    subcategories: [
      "PVC Mouldings",
      "Wooden Mouldings",
      "Decorative Profiles"
    ],
    products: [
      {
        id: "mp-01",
        name: "HDHMR Wall Moulding",
        category: "Mouldings & Profiles",
        subcategory: "Decorative Profiles",
        image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
        specs: "Precision-milled water resistant HDHMR moulding profile ready for seamless seamless spray painting.",
        material: "High Density Moisture Resistant Fiber",
        finish: "Pre-Primed Smooth White",
        dimensions: "2440mm x 45mm x 18mm",
        applications: "French Wainscoting, Neo-Classical Wall Frames, Door Architraves"
      },
      {
        id: "mp-02",
        name: "Wooden Wall Moulding",
        category: "Mouldings & Profiles",
        subcategory: "Wooden Mouldings",
        image: "https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=800&q=80",
        specs: "Solid seasoned teak and white ash timber moulding with deep classical step contours.",
        material: "100% Solid Seasoned Teakwood",
        finish: "Natural Woodgrain Sanded",
        dimensions: "2440mm x 60mm x 22mm",
        applications: "Classic Picture Railings, Baseboards, Ceiling Cornices"
      },
      {
        id: "mp-03",
        name: "PVC Wall Moulding",
        category: "Mouldings & Profiles",
        subcategory: "PVC Mouldings",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Lightweight flexible polymer moulding suitable for straight and subtly curved wall applications.",
        material: "Extruded High-Impact Polymer",
        finish: "Matte Off-White",
        dimensions: "2400mm x 40mm x 15mm",
        applications: "Residential Wainscoting, Mirror Framing, Panel Borders"
      },
      {
        id: "mp-04",
        name: "PVC Wall Moulding Patti",
        category: "Mouldings & Profiles",
        subcategory: "PVC Mouldings",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
        specs: "Slim flat moulding strip with chamfered edges designed for minimalist modern wall grid dividing.",
        material: "Rigid Virgin PVC",
        finish: "Smooth Matt Paintable",
        dimensions: "2440mm x 25mm x 8mm",
        applications: "Grid Wall Treatments, Headboard Framing"
      },
      {
        id: "mp-05",
        name: "Wooden Moulding Patti",
        category: "Mouldings & Profiles",
        subcategory: "Wooden Mouldings",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Solid wood beading strip precision-milled for edge protection and panel border inlays.",
        material: "Seasoned Red Hardwood",
        finish: "Raw Sanded / Teak Polish",
        dimensions: "2440mm x 20mm x 12mm",
        applications: "Cabinet Edging, Glass Beading, Shutter Frames"
      },
      {
        id: "mp-06",
        name: "Carving Corner Moulding",
        category: "Mouldings & Profiles",
        subcategory: "Wooden Mouldings",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Intricate floral and acanthus leaf corner rosettes designed to connect wainscoting borders.",
        material: "Hand-Carved Seasoned Timber / Polyresin",
        finish: "Antique Gold / Paintable Matte",
        dimensions: "120mm x 120mm x 25mm",
        applications: "Ceiling Centerpieces, Wall Frame Corners, Classical Door Frames"
      },
      {
        id: "mp-07",
        name: "Stainless Steel Decorative Profiles",
        category: "Mouldings & Profiles",
        subcategory: "Decorative Profiles",
        image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        specs: "SS304 grade PVD coated titanium gold, rose gold, and black T-profiles, U-channels, and L-angles.",
        material: "Grade 304 Stainless Steel (0.8mm - 1.2mm)",
        finish: "Mirror / Brushed Champagne Gold PVD",
        dimensions: "2440mm x (6mm/10mm/15mm/20mm)",
        applications: "Tile Transition Gaps, Wood Wall Inlays, Wardrobe Shutter Accents"
      }
    ]
  },
  {
    id: "furniture",
    hash: "furniture",
    number: "07",
    name: "Furniture",
    tagline: "Ergonomic Office Seating & Handcrafted Executive Millwork",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/furniture.webp",
    description: "Ergonomically engineered executive chairs, boardroom tables, luxury reception lounges, commercial seating, and custom cabinetry crafted with premium materials.",
    productCountText: "13+ PRODUCTS AVAILABLE",
    subcategories: [
      "Office Chairs",
      "Commercial Chairs",
      "Office Furniture"
    ],
    products: [
      {
        id: "fn-01",
        name: "High Back Office Chair",
        category: "Furniture",
        subcategory: "Office Chairs",
        image: "https://images.unsplash.com/photo-1580481077197-0b168db7483d?auto=format&fit=crop&w=800&q=80",
        specs: "Multi-position synchro-tilt mechanism, adjustable lumbar support, 4D armrests, and Class 4 gas lift.",
        material: "Die-Cast Aluminum Base + High Tensile Korean Mesh",
        finish: "Matte Black & Polished Aluminum",
        dimensions: "W 650mm x D 650mm x H 1180-1280mm",
        applications: "Executive Cabins, Engineering Desks, Long-Shift Workspaces"
      },
      {
        id: "fn-02",
        name: "Boss Chair",
        category: "Furniture",
        subcategory: "Office Chairs",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
        specs: "Full-grain bonded leather upholstery with memory foam cushioning and heavy-duty wooden armrests.",
        material: "Solid Timber Frame + High-Grade Nappa Leather",
        finish: "Espresso Brown & Polished Mahogany",
        dimensions: "W 720mm x D 700mm x H 1220mm",
        applications: "Managing Director Suites, Boardrooms, Presidential Offices"
      },
      {
        id: "fn-03",
        name: "Revolving Chair",
        category: "Furniture",
        subcategory: "Office Chairs",
        image: "https://images.unsplash.com/photo-1580481077197-0b168db7483d?auto=format&fit=crop&w=800&q=80",
        specs: "360-degree smooth swivel chair with pneumatic height adjustment and nylon twin-wheel castors.",
        material: "Nylon Fiber Shell with Breathable Cushion",
        finish: "Charcoal Grey / Cobalt Blue Fabric",
        dimensions: "W 600mm x D 580mm x H 950-1050mm",
        applications: "Staff Workstations, BPO Centers, Home Study Desks"
      },
      {
        id: "fn-04",
        name: "Mesh Chair",
        category: "Furniture",
        subcategory: "Office Chairs",
        image: "https://images.unsplash.com/photo-1580481077197-0b168db7483d?auto=format&fit=crop&w=800&q=80",
        specs: "All-mesh ventilated ergonomic task chair providing complete airflow and spinal contouring.",
        material: "Glass-Filled Nylon Frame + Elastomeric Mesh",
        finish: "Monochrome Black",
        dimensions: "W 620mm x D 600mm x H 1020mm",
        applications: "Open Plan Co-Working Spaces, Tech Companies"
      },
      {
        id: "fn-05",
        name: "Leather Chair",
        category: "Furniture",
        subcategory: "Office Chairs",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
        specs: "Ribbed mid-century modern aesthetic with genuine leather padded cushions and chrome cantilever frame.",
        material: "Chrome Plated Tubular Steel + Top Grain Leather",
        finish: "Cognac Tan / Classic Ivory",
        dimensions: "W 580mm x D 600mm x H 920mm",
        applications: "Conference Rooms, Design Agencies, Private Consultation Desks"
      },
      {
        id: "fn-06",
        name: "Mid Back Chair",
        category: "Furniture",
        subcategory: "Office Chairs",
        image: "https://images.unsplash.com/photo-1580481077197-0b168db7483d?auto=format&fit=crop&w=800&q=80",
        specs: "Compact mid-back ergonomic chair tailored for meeting rooms and conference tables.",
        material: "Molded Foam with Heavy Cotton Fabric",
        finish: "Heather Slate Fabric",
        dimensions: "W 590mm x D 560mm x H 940mm",
        applications: "Meeting Rooms, Training Rooms, Reception Workstations"
      },
      {
        id: "fn-07",
        name: "Office Fix Chair",
        category: "Furniture",
        subcategory: "Commercial Chairs",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
        specs: "Heavy-gauge non-revolving sled base visitor chair with anti-tip floor glides.",
        material: "Powder Coated Black Steel Tube + High-Density Foam",
        finish: "Matte Black & Black Leatherette",
        dimensions: "W 550mm x D 560mm x H 880mm",
        applications: "Visitor Seating, Waiting Lounges, Hospital Consultation Rooms"
      },
      {
        id: "fn-08",
        name: "Restaurant Chair",
        category: "Furniture",
        subcategory: "Commercial Chairs",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
        specs: "Commercial-grade stain-resistant dining chair with reinforced curved back and solid wood legs.",
        material: "Solid Beechwood Legs + Water-Repellent Velvet",
        finish: "Emerald Green / Warm Mustard / Walnut",
        dimensions: "W 520mm x D 540mm x H 840mm",
        applications: "Fine Dining Restaurants, Boutique Cafes, Clubhouses"
      },
      {
        id: "fn-09",
        name: "Bar Chair",
        category: "Furniture",
        subcategory: "Commercial Chairs",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Height-adjustable swivel bar stool with 360-degree footrest and brass metallic accents.",
        material: "Electroplated Brass Base + Leather Swivel Seat",
        finish: "Champagne Gold & Saddle Leather",
        dimensions: "W 450mm x D 450mm x H 900-1100mm",
        applications: "Kitchen Breakfast Islands, Rooftop Bars, Hotel Lounges"
      },
      {
        id: "fn-10",
        name: "School Chair",
        category: "Furniture",
        subcategory: "Commercial Chairs",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
        specs: "Durable ergonomic polypropylene shell chair with integrated writable tablet arm option.",
        material: "High-Impact Polypropylene + Steel Frame",
        finish: "Vibrant School Navy / Olive",
        dimensions: "W 480mm x D 500mm x H 780mm",
        applications: "Educational Institutions, Training Academies, Auditoriums"
      },
      {
        id: "fn-11",
        name: "Office Sofa",
        category: "Furniture",
        subcategory: "Office Furniture",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
        specs: "Clean architectural 3-seater modular sofa with high-resilience foam and brushed steel base.",
        material: "Kiln-Dried Hardwood Frame + High GSM Linen Fabric",
        finish: "Charcoal Grey & Brushed Steel Legs",
        dimensions: "W 2100mm x D 850mm x H 780mm",
        applications: "Corporate Lobbies, Executive Lounges, Founder Cabins"
      },
      {
        id: "fn-12",
        name: "Executive Cabin Table",
        category: "Furniture",
        subcategory: "Office Furniture",
        image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
        specs: "Monolithic luxury executive desk with integrated wireless charging, leather writing pad, and return credenza.",
        material: "Smoked Oak Veneer + Calacatta Quartz Waterfall + Steel",
        finish: "Matte Walnut & Brushed Gold Accent",
        dimensions: "W 2400mm x D 1000mm x H 750mm",
        applications: "Director Offices, Law Firms, Corporate Headquarters"
      },
      {
        id: "fn-13",
        name: "Metal Storage Rack",
        category: "Furniture",
        subcategory: "Office Furniture",
        image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80",
        specs: "Heavy-duty modular steel shelving with adjustable tiers and anti-corrosion electrostatic coating.",
        material: "Cold-Rolled Carbon Steel",
        finish: "Textured Matte Industrial Black Powder Coat",
        dimensions: "W 1200mm x D 450mm x H 2000mm",
        applications: "Architectural Material Sample Stores, Office Archives, Storage Vaults"
      }
    ]
  },
  {
    id: "flooring",
    hash: "flooring",
    number: "08",
    name: "Flooring",
    tagline: "Natural Hardwood Planks, SPC Stone Composites & Resilient Surfaces",
    image: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/flooring.webp",
    description: "Discover AC4/AC5 grade wooden laminate flooring, 100% waterproof SPC stone polymer planks, heavy-duty vinyl sheets, and luxury landscape turf engineered for high-traffic longevity.",
    productCountText: "5+ PRODUCTS AVAILABLE",
    subcategories: [
      "Wooden Flooring",
      "Vinyl Flooring",
      "SPC Flooring",
      "Artificial Grass"
    ],
    products: [
      {
        id: "fl-01",
        name: "Wooden Laminate Flooring",
        category: "Flooring",
        subcategory: "Wooden Flooring",
        image: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=800&q=80",
        specs: "AC4 commercial traffic rating with Uniclic floating tongue-and-groove joint and thermal underlay.",
        material: "High-Density Fiberboard (HDF) + Aluminum Oxide Overlay",
        finish: "Natural Brushed Oak & Smoked Walnut",
        dimensions: "1215mm x 195mm x 8.3mm / 12mm",
        applications: "Master Bedrooms, Living Rooms, High-End Boutiques"
      },
      {
        id: "fl-02",
        name: "PVC Vinyl Flooring",
        category: "Flooring",
        subcategory: "Vinyl Flooring",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Seamless roll vinyl with antimicrobial coating, anti-slip R10 rating, and sound absorption.",
        material: "Calendered Heterogeneous PVC",
        finish: "Polished Concrete & Terrazzo Effect",
        dimensions: "2000mm Width Roll x 2.0mm Thickness",
        applications: "Hospitals, Clinics, Fitness Gyms, Daycares"
      },
      {
        id: "fl-03",
        name: "SPC Wooden Flooring",
        category: "Flooring",
        subcategory: "SPC Flooring",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Stone Plastic Composite rigid core with 100% waterproof guarantee and IXPE acoustic backing.",
        material: "70% Natural Limestone + 30% PVC Polymer",
        finish: "Synchronized Deep Embossed Woodgrain",
        dimensions: "1220mm x 180mm x 5.0mm (+1.5mm IXPE pad)",
        applications: "Kitchens, Basements, Penthouse Terraces, Entire Homes"
      },
      {
        id: "fl-04",
        name: "PVC Vinyl Plank Flooring",
        category: "Flooring",
        subcategory: "Vinyl Flooring",
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
        specs: "Luxury Vinyl Tile (LVT) self-adhesive or click planks with 0.5mm wear layer for commercial use.",
        material: "Virgin Polymer LVT",
        finish: "Grey Sawn Timber Texture",
        dimensions: "914mm x 152mm x 2.5mm / 3.0mm",
        applications: "Commercial Offices, Retail Stores, Co-Living Spaces"
      },
      {
        id: "fl-05",
        name: "Artificial Grass Carpet",
        category: "Flooring",
        subcategory: "Artificial Grass",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "UV-treated realistic 4-tone grass yarn with high stitch density and rapid rainwater drainage backing.",
        material: "Polyethylene & Polypropylene Monofilament",
        finish: "Natural Spring Green (35mm / 45mm Pile Height)",
        dimensions: "2000mm / 4000mm Width Rolls",
        applications: "Balcony Gardens, Terrace Sit-Outs, Courtyards, Sports Lawns"
      }
    ]
  },
  {
    id: "decorative-materials",
    hash: "decorative-materials",
    number: "09",
    name: "Decorative Materials",
    tagline: "Natural Wood Veneers, Rattan Weaves & Specialty Surfaces",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/decorative-materials.webp",
    description: "Exquisite natural wood veneers, 3D embossed wood sheets, natural cork insulation, handwoven rattan webbing, and premium door skin overlays.",
    productCountText: "9+ PRODUCTS AVAILABLE",
    subcategories: [
      "Veneers",
      "Cork & Cane",
      "Door Skins"
    ],
    products: [
      {
        id: "dm-01",
        name: "Wood Veneer",
        category: "Decorative Materials",
        subcategory: "Veneers",
        image: "https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=800&q=80",
        specs: "0.55mm genuine sliced natural wood veneer fleece-backed for seamless architectural application.",
        material: "American Walnut / Smoked Oak Natural Sliced Veneer",
        finish: "Raw Natural Grain (Ready for Melamyne/PU Polish)",
        dimensions: "2440mm x 1220mm x 0.55mm",
        applications: "Bespoke Wardrobe Doors, Credenzas, Living Room Feature Walls"
      },
      {
        id: "dm-02",
        name: "3D Embossed Veneer",
        category: "Decorative Materials",
        subcategory: "Veneers",
        image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
        specs: "Thermo-mechanically embossed geometric and ripple textures permanently pressed into natural wood.",
        material: "Natural Engineered Veneer on Phenolic Backer",
        finish: "Deep 3D Wave & Diamond Relief",
        dimensions: "2440mm x 1220mm x 1.5mm",
        applications: "Feature Pillars, Reception Fronts, Main Entrance Portals"
      },
      {
        id: "dm-03",
        name: "Cork Sheet",
        category: "Decorative Materials",
        subcategory: "Cork & Cane",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
        specs: "100% natural agglomerated cork sheet providing thermal insulation, pinability, and acoustic absorption.",
        material: "Natural Cork Granules with Non-Toxic Polyurethane Binder",
        finish: "Fine Natural Granular Texture",
        dimensions: "915mm x 610mm x (3mm/6mm/10mm)",
        applications: "Acoustic Wall Cladding, Vision Boards, Sustainable Interiors"
      },
      {
        id: "dm-04",
        name: "Rattan Cane Webbing",
        category: "Decorative Materials",
        subcategory: "Cork & Cane",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
        specs: "Handwoven Indonesian natural rattan radio weave cane webbing with high tensile flexibility.",
        material: "100% Organic Grade A Rattan",
        finish: "Natural Honey Rattan Weave",
        dimensions: "600mm / 900mm Width Rolls",
        applications: "Wardrobe Shutters, Sideboards, Bohemian Headboards"
      },
      {
        id: "dm-05",
        name: "Door Skins",
        category: "Decorative Materials",
        subcategory: "Door Skins",
        image: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=800&q=80",
        specs: "High-density molded and flat decorative skins designed for instant flush door transformation.",
        material: "Melamine Impregnated HDF",
        finish: "Textured Teak & Metallic Foil Inlay",
        dimensions: "2135mm x 915mm x 3.0mm",
        applications: "Interior Residential Doors, Hotel Rooms"
      },
      {
        id: "dm-06",
        name: "Digital Door Paper Print",
        category: "Decorative Materials",
        subcategory: "Door Skins",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "High-resolution digital UV print sheets featuring bespoke architectural murals and ethnic art.",
        material: "UV Coated Synthetic Film",
        finish: "High Gloss / Matte Anti-Scratch",
        dimensions: "2135mm x 915mm",
        applications: "Feature Entrance Doors, Puja Room Doors"
      },
      {
        id: "dm-07",
        name: "PVC Door Skin",
        category: "Decorative Materials",
        subcategory: "Door Skins",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        specs: "Molded waterproof PVC overlay skin with woodgrain embossing for wet-area doors.",
        material: "Extruded Rigid Polymer Membrane",
        finish: "Walnut & Rosewood Woodgrain",
        dimensions: "2050mm x 850mm x 2.0mm",
        applications: "Bathroom Flush Doors, Balcony Doors"
      },
      {
        id: "dm-08",
        name: "Designer Laminate Door Skin",
        category: "Decorative Materials",
        subcategory: "Door Skins",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        specs: "Dual-tone synchronized laminate door skin with metallic accent ribbons.",
        material: "High Pressure Phenolic Skin",
        finish: "Smoked Ash & Champagne Brass Line",
        dimensions: "2135mm x 915mm x 1.0mm",
        applications: "Master Suite Entrances, Apartment Main Doors"
      },
      {
        id: "dm-09",
        name: "Plywood Door Skin",
        category: "Decorative Materials",
        subcategory: "Door Skins",
        image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80",
        specs: "Gurjan face plywood pre-grooved with vertical and horizontal architectural relief lines.",
        material: "Calibrated 3-Ply Timber",
        finish: "Sanded Natural Hardwood Face",
        dimensions: "2135mm x 915mm x 3.5mm",
        applications: "Solid Wood Finish Flush Doors"
      }
    ]
  },
  {
    id: "interior-solutions",
    hash: "interior-solutions",
    number: "10",
    name: "Interior Solutions",
    tagline: "Custom Corian Temples, CNC Laser Precision & Architectural Jali Work",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
    localImage: "assets/products/categories/interior-solutions.webp",
    description: "Custom-fabricated Corian mandirs and temples, 0.1mm CNC laser fretwork jalis, 3D architectural bas-relief carving, and bespoke turnkey spatial installations.",
    productCountText: "6+ PRODUCTS AVAILABLE",
    subcategories: [
      "Temple Architecture",
      "CNC Cutting",
      "Jali Work"
    ],
    products: [
      {
        id: "is-01",
        name: "Corian Temple",
        category: "Interior Solutions",
        subcategory: "Temple Architecture",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        specs: "Seamless DuPont Corian solid surface mandir with integrated warm backlight LED channels and CNC engraving.",
        material: "12mm DuPont / Staron Solid Surface",
        finish: "Glacier White Satin Seamless Joint",
        dimensions: "Custom Architectural Dimensions (e.g. 1500mm x 600mm x 2100mm)",
        applications: "Private Residence Puja Rooms, Luxury Penthouse Temples"
      },
      {
        id: "is-02",
        name: "CNC Laser Cutting",
        category: "Interior Solutions",
        subcategory: "CNC Cutting",
        image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        specs: "0.1mm tolerance high-precision laser cutting on brass, mild steel, stainless steel, and aluminum sheets.",
        material: "SS304 / Brass / MS / Aluminum",
        finish: "PVD Gold / Powder Coated / Raw Polished",
        dimensions: "Up to 3000mm x 1500mm single bed sheet",
        applications: "Exterior Facade Screens, Staircase Railing Panels, Main Gate Inserts"
      },
      {
        id: "is-03",
        name: "3D Carving Design",
        category: "Interior Solutions",
        subcategory: "CNC Cutting",
        image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
        specs: "Multi-axis 3D relief sculpting in solid wood, HDHMR, stone, and Corian with organic sculptural depth.",
        material: "HDHMR / Solid Hardwood / Composite Stone",
        finish: "Multi-Coat Deco Polyurethane Paint",
        dimensions: "2440mm x 1220mm x (25mm - 50mm relief depth)",
        applications: "Feature Wall Art, Reception Backgrounds, Ceiling Murals"
      },
      {
        id: "is-04",
        name: "CNC Jali Cutting",
        category: "Interior Solutions",
        subcategory: "Jali Work",
        image: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=800&q=80",
        specs: "Intricate Moroccan, Islamic, and contemporary geometric perforated screens for spatial zoning.",
        material: "18mm HDHMR / WPC / Corian Board",
        finish: "Flawless CNC Edge-Sanded & Primed",
        dimensions: "2440mm x 1220mm x 18mm",
        applications: "Room Dividers, Ceiling Insets, Window Privacy Screens"
      },
      {
        id: "is-05",
        name: "Wooden Jali Door",
        category: "Interior Solutions",
        subcategory: "Jali Work",
        image: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=800&q=80",
        specs: "Solid hardwood framed door featuring intricate central fretwork jali with clear glass sandwich.",
        material: "Seasoned Teakwood + Toughened Glass",
        finish: "Hand-Polished Antique Teak",
        dimensions: "2100mm x 900mm x 40mm",
        applications: "Mandir Doors, Living Room Partitions, Vestibule Entrances"
      },
      {
        id: "is-06",
        name: "Decorative Jali Work",
        category: "Interior Solutions",
        subcategory: "Jali Work",
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
        specs: "Backlit decorative jali panel assemblies with integrated acoustic backing felt and diffusers.",
        material: "Gold Leafed Polymer Jali + Acoustic Felt",
        finish: "Metallic Gold Leaf & Smoked Felt",
        dimensions: "2440mm x 1220mm x 25mm",
        applications: "Home Theater Walls, Banquet Entrances, Private Dining Rooms"
      }
    ]
  }
];

// Contact information constants
const SHAYONA_CONTACT = {
  phone: "8619097651",
  salesPhone: "7300048604",
  whatsappNumber: "919887506604",
  email: "shayonainteriors@gmail.com",
  location: "Shayona Enterprises, Jaipur, Rajasthan, India",
  websiteUrl: "https://shayonainteriors.in/",
  indiamartUrl: "https://www.indiamart.com/shayonaenterprises/profile.html?srsltid=AfmBOopv41MZ3wa3xji316v8KnAVyCRIwlIHDyZykCg-fkU3xx_N8nfF",
  instagramUrl: "https://www.instagram.com/shayona_interiors/",
  youtubeUrl: "https://www.youtube.com/@shayonaInteriors"
};
